// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coFind.Infrastructure.Data;

#nullable disable

namespace coFind.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901190000_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("coFind.Domain.Entities.Offer", b =>
            {
                b.Property<int>("OfferId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("Industry").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsAvailable").HasColumnType("bit");
                b.Property<string>("Location").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("Role").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.PrimitiveCollection<string>("Skills").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Title").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("OfferId");
                b.HasIndex("UserId");
                b.ToTable("Offers");
            });

            modelBuilder.Entity("coFind.Domain.Entities.RefreshToken", b =>
            {
                b.Property<int>("RefreshTokenId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                b.Property<string>("TokenHash").IsRequired().HasMaxLength(128).HasColumnType("nvarchar(128)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("RefreshTokenId");
                b.HasIndex("TokenHash").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens");
            });

            modelBuilder.Entity("coFind.Domain.Entities.User", b =>
            {
                b.Property<int>("UserId").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("WhatsappNumber").IsRequired().HasMaxLength(15).HasColumnType("nvarchar(15)");
                b.HasKey("UserId");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("coFind.Domain.Entities.Offer", b =>
            {
                b.HasOne("coFind.Domain.Entities.User", "Owner")
                    .WithMany("Offers")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Owner");
            });

            modelBuilder.Entity("coFind.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("coFind.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("coFind.Domain.Entities.User", b => b.Navigation("Offers"));
#pragma warning restore 612, 618
        }
    }
}